In [159]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [160]:
!pip install numpy
import numpy as np

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [161]:
df=pd.read_csv("/content/sample_data/movies_metadata.csv")

/tmp/ipykernel_2703/2414992942.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/sample_data/movies_metadata.csv")

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [163]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [164]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [165]:
df.duplicated().sum()

np.int64(13)

In [166]:
df=df.drop_duplicates().reset_index(drop=True)

In [167]:
df.duplicated().sum()

np.int64(0)

In [168]:
df=df[['title','overview','genres','vote_average','popularity']]

In [169]:
df.head()

,title,overview,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",5.7,8.387519

In [170]:
df.isnull().sum()

title             6
overview        954
genres            0
vote_average      6
popularity        5
dtype: int64

In [171]:
df=df.dropna(subset=['title'])

In [172]:
df['overview']=df['overview'].fillna('')

In [173]:
import ast
def convert_genres(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return " ".join(L)

In [174]:
df['genres']=df['genres'].apply(convert_genres)

In [175]:
df.iloc[0]['genres']

'Animation Comedy Family'

In [176]:
df.head()

,title,overview,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,5.7,8.387519

In [177]:
df.isnull().sum()

title           0
overview        0
genres          0
vote_average    0
popularity      0
dtype: int64

In [178]:
df['features']=df['overview']+" "+df['genres']

In [179]:
df['features'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family"

In [180]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [181]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [182]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [183]:
def preprocess(text):
  #convert to lower case
  text = str(text).lower()

  #remove non alphabetic chars
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  #tokenization
  words = text.split()

  #remove stopwords e.g is,a
  words = [word for word in words if word not in stop_words]

  #lemmatization e.g running or runs comes to root form run
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

# Apply preprocessing to the 'features' column
df['features'] = df['features'].apply(preprocess)

In [184]:
df['features'].head()

0    led woody andys toy live happily room andys bi...
1    sibling judy peter discover enchanted board ga...
2    family wedding reignites ancient feud nextdoor...
3    cheated mistreated stepped woman holding breat...
4    george bank recovered daughter wedding receive...
Name: features, dtype: object

In [185]:

# Drop rows with duplicate titles so each title is unique
df = df.drop_duplicates(subset=['title']).reset_index(drop=True)

#find row number of a movie using its title
indices = pd.Series(df.index, index=df['title'])

In [187]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Caged Heat 3000                42272
Subdue                         42273
Century of Birthing            42274
Satan Triumphant               42275
Queerama                       42276
Length: 42277, dtype: int64

In [188]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [189]:
movies=TfidfVectorizer(
    max_features=50000,
    ngram_range=(1,2),
    stop_words='english',
    min_df=2,
    max_df=0.9
)
# min_df removes noise words that appear in very few documents ,max_df removes words very common
# ngram word and word pairs

In [190]:
movies_matrix = movies.fit_transform(df['features'])

In [191]:
movies_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1364483 stored elements and shape (42277, 50000)>

In [192]:
from sklearn.metrics.pairwise import cosine_similarity

In [193]:
def recommend(movie, n=10):
    if movie not in indices:
        return "Movie not found"

    idx = indices[movie]

   # Compute similarities and compares movie similarity to other movies in dataset
    similarity_scores = cosine_similarity(
        movies_matrix[idx],
        movies_matrix
    ).flatten()

    # Get top matches by argsort[::-1] returns [[indices sorted in reverse order of similarity]] [1:n+1] skips 0th index movie
    similar_indices = similarity_scores.argsort()[::-1][1:n+1]

    # Return the titles from the dataframe
    return df['title'].iloc[similar_indices]

In [194]:
def recommend_and_scores(movie, n=10):
    if movie not in indices:
        return "Movie not found"

    idx = indices[movie]

    # Compute similarity scores
    similarity_scores = cosine_similarity(
        movies_matrix[idx],
        movies_matrix
    ).flatten()

    # Get top matches excluding the movie itself
    similar_indices = similarity_scores.argsort()[::-1][1:n+1]

    # Create a DataFrame with titles and their respective scores
    recommendations = pd.DataFrame({
        'title': df['title'].iloc[similar_indices].values,
        'similarity_score': similarity_scores[similar_indices]
    })

    return recommendations

In [195]:
recommend_and_scores('Avatar',10)

                                    title  similarity_score
0                                Avatar 2          0.293988
1                    Stand by Me Doraemon          0.264831
2                   The War of the Robots          0.248787
3  The Flash 2 - Revenge of the Trickster          0.247121
4                    Frank Herbert's Dune          0.205043
5                          Thor: Ragnarok          0.202624
6                  Moontrap: Target Earth          0.200507
7                       Project Moon Base          0.196694
8                    The Inhabited Island          0.195700
9                                  Désiré          0.187180

In [196]:
recommend('Batman',10)

8993                    Batman Beyond: Return of the Joker
17469                                The Dark Knight Rises
30134                     Batman Unlimited: Monster Mayhem
23889                                    Batman vs Dracula
150                                         Batman Forever
25323                                              Groupie
14924                           Batman: Under the Red Hood
1487                                        Batman & Robin
23740    1½ Knights - In Search of the Ravishing Prince...
12425                                Batman: Gotham Knight
Name: title, dtype: object

In [197]:
recommend('Avatar',5)

25061                                  Avatar 2
26938                      Stand by Me Doraemon
17237                     The War of the Robots
33657    The Flash 2 - Revenge of the Trickster
7330                       Frank Herbert's Dune
Name: title, dtype: object

In [198]:
import pickle

pickle.dump(movies_matrix,open('movies_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(movies,open('movies.pkl','wb'))